# Setup
title:               Foundations
tagline:             'The simplest service blueprint for your org'
description:         'Painfully curated to allow you to focus only on the parts that matter.'
url:                 https://huxpopa.github.io/foundations/
baseurl:             ''
paginate:            5
permalink:           pretty

# Gems
plugins:
  - jekyll-paginate

# About/contact
author:
  name:              Derek
  url:               #https://twitter.com/future-handle
  email:             #email@email.something

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
