# Setup
title:               Foundations
tagline:             'A simple blueprint for the boring parts of your organization'
description:         'Painfully curated and simplified to only the parts that help.'
url:                 #future
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Derek
  url:               #https://twitter.com/futureHandle
  email:             #future@email.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
